name: DCA $DMC Scan

on:
  schedule:
    # Jalan tiap 1 jam
    - cron: '*/57 * * * *'
  workflow_dispatch: # Biar bisa di-klik Run manual kalau mau tes

# --- IZIN MENULIS (TAMBAHAN 1) ---
permissions:
  contents: write
# ---------------------------------

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas yfinance pycoingecko requests

      - name: Run Robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GETPOSITION: 1
          COINID: 'delorean'
          ISDAILY: 1
          ISDCA: 1
        run: python analytics-signal.py